name: shfmt
description: shfmt action
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/github-action-format@v0.1.1
      with:
        github_token: ${{ inputs.github_token }}
        command: git ls-files | grep -E "\.sh$" | xargs shfmt -w -s -l
        commit_message: "style: shfmt"
